config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
    resources :reviews
  end

  resources :chefs, except: [:new, :destroy]
  get '/register', to: 'chefs#new'

  get '/login', to: 'logins#new'
  post 'login', to: 'logins#create'
  get 'logout', to: 'logins#destroy'

  resources 'styles', only: [:new, :create, :show]
  resources 'ingredients', only: [:new, :create, :show]

end

app/views/pages/home.html.erb
<div class= "center jumbotron">
  <h1>Welcome to MyRecipes App</h1>
  <h2>here you can include your new recipes</h2>
  <%= link_to "Sign Up now!", register_path, class: "btn btn-lg btn-success"%>
</div>
<div class="row">
  <div class="col-md-4">
    <h3 class="midrow">
      view recipes as guest user
    </h3>
    <h2 class="left">
      Browse and view recipes and sign up later
    </h2>
    <p><%= link_to "browse recipes listing", recipes_path, class:"btn btn-warning btn-small"%></p>
  </div>

  <div class="col-md-4">
    <h3 class="midrow">
      Sign in to your account
    </h3>
    <h2 class="left">
      Add/update your recipe/create reviews/like-dislike
    </h2>
    <p><%= link_to "login to your account", login_path, class:"btn btn-warning btn-small"%></p>
  </div>

  <div class="col-md-4">
    <h3 class="midrow">
      view recipes as guest user
    </h3>
    <h2 class="left">
      Browse and view recipes and sign up later
    </h2>
    <p><%= link_to "browse recipes listing", "", class:"btn btn-warning btn-small"%></p>
  </div>
</div>